### ISSUE TITLE
error on confirming purchase at /purchases/confirm/1

### ISSUE THREAD

**Issue by galzuntpanz** [galzuntpanz/BitWasp#5]
:  Uncaught exception 'InvalidArgumentException' with message 'Unsupported magic byte' in /var/www/bitwasp/vendor/bitwasp/bitcoin-lib/src/BIP32.php:415
Stack trace:
#0 /var/www/bitwasp/vendor/bitwasp/bitcoin-lib/src/BIP32.php(251): BitWasp\BitcoinLib\BIP32::import('password')
#1 /var/www/bitwasp/vendor/bitwasp/bitcoin-lib/src/BIP32.php(331): BitWasp\BitcoinLib\BIP32::get_definition_tuple('password', '0')
#2 /var/www/bitwasp/application/models/Bip32_model.php(68): BitWasp\BitcoinLib\BIP32::build_key('password', '0')
#3 /var/www/bitwasp/application/models/Bip32_model.php(114): Bip32_model->recurse_until_unique_bip32_key(Array)
#4 /var/www/bitwasp/application/models/Order_model.php(359): Bip32_model->get_next_admin_child()
#5 /var/www/bitwasp/application/controllers/Orders.php(332): Order_model->vendor_accept_order(Array)
#6 [internal function]: Orders->buyer_confirm('1')
#7 /var/www/bitwasp/system/core/CodeIgniter.php(473): call_user_func_array(Array, Array)
#8 /var/www/bitwasp/index.php(282): require_once('/var/w in 
/var/www/bitwasp/vendor/bitwasp/bitcoin-lib/src/BIP32.php on line 415

**Comment by galzuntpanz** [comment]
this bug was because i provided invalid bip32 public key in first `/install/` operation

**Comment by galzuntpanz** [comment]
it is an extended public key, but are there any tools to validate them?
This snippet uses try/catch for validation method http://pastebin.com/5ZkS5BjE

**Comment by galzuntpanz** [comment]
vendor/bitwasp/bitcoin-lib/src/BIP32.phpの中でimportしてるのと同じことをすればよさそう

**Comment by galzuntpanz** [comment]
fixed in f019fe24a5dcf8b91211bed6c8699b05fc6991ab
